In [20]:
# 한글폰트 사용
import platform
from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':
    f_path = '/Library/Fonts/Arial Unicode.ttf'
elif platform.system() == 'Windows':
    f_path = 'c:/Windows/Fonts/malgun.ttf'
font_name = font_manager.FontProperties(fname=f_path).get_name()
rc('font', family=font_name)

print('Hangul font is set!')

Hangul font is set!

In [19]:
# 필요패키지 import
import numpy as np
import pandas as pd
from datetime import datetime
import csv # csv 파일 저장
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [21]:
## geopy로 주소 간단하게 지오코딩 하는 법
from geopy.geocoders import Nominatim
import osmnx as ox

ModuleNotFoundError: No module named 'osmnx'

In [22]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [62]:
df = pd.read_csv('DATA/시군구_자동차_등록현황_2021_10.csv', engine='python')
df

      시       군구   자동차 등록 현황
0    서울       강남     238,244
1    서울       강동     152,372
2    서울       강북      75,389
3    서울       강서     204,285
4    서울       관악     118,529
5    서울       광진      98,364
6    서울       구로     145,204
7    서울       금천      89,891
8    서울       노원     152,145
9    서울       도봉      95,745
10   서울      동대문      98,427
11   서울       동작     106,156
12   서울       마포     121,224
13   서울      서대문      89,451
14   서울       서초     177,928
15   서울       성동     106,348
16   서울       성북     121,263
17   서울       송파     246,647
18   서울       양천     151,317
19   서울      영등포     146,188
20   서울       용산      79,619
21   서울       은평     132,712
22   서울       종로      50,258
23   서울        중      61,930
24   서울       중랑     114,325
25   서울        계   3,173,961
26   부산       강서      85,620
27   부산       금정      88,347
28   부산       기장      83,626
29   부산        남     100,847
30   부산        동      57,009
31   부산       동래      96,440
32   부산      부산진     143,182
33   부산        북     106,063
34   부산       사상      89,145
35   부산       사하     113,846
36   부산        서      30,681
37   부산       수영     104,965
38   부산       연제     104,488
39   부산       영도      33,470
40   부산        중      37,426
41   부산      해운대     181,829
42   부산        계   1,456,984
43   대구        남      57,794
44   대구       달서     286,275
45   대구       달성     141,955
46   대구        동     166,008
47   대구        북     210,306
48   대구        서      72,207
49   대구       수성     214,023
50   대구        중      61,368
51   대구        계   1,209,936
52   인천       강화      53,600
53   인천       계양     304,413
54   인천       남동     306,100
55   인천        동      27,486
56   인천      미추홀     169,090
57   인천       부평     249,518
58   인천        서     258,220
59   인천       연수     208,286
60   인천       옹진      12,686
61   인천        중      80,045
62   인천        계   1,669,444
63   광주       광산     210,391
64   광주        남      94,984
65   광주        동      45,031
66   광주        북     200,103
67   광주        서     147,924
68   광주        계     698,433
69   대전       대덕      93,017
70   대전        동      96,524
71   대전        서     215,663
72   대전       유성     183,762
73   대전        중     102,115
74   대전        계     691,081
75   울산        남     161,974
76   울산        동      63,179
77   울산        북     119,296
78   울산       울주     132,244
79   울산        중     103,132
80   울산        계     579,825
81   세종   세종특별자치     182,919
82   세종        계     182,919
83   경기       가평      32,295
84   경기    고양 덕양     188,121
85   경기   고양 일산동     131,845
86   경기   고양 일산서     121,238
87   경기       과천      27,306
88   경기       광명     105,277
89   경기       광주     204,116
90   경기       구리      73,443
91   경기       군포     103,749
92   경기       김포     237,235
93   경기      남양주     315,280
94   경기      동두천      40,140
95   경기       부천     308,449
96   경기    성남 분당     194,196
97   경기    성남 수정      79,981
98   경기    성남 중원      75,968
99   경기    수원 권선     200,691
100  경기    수원 영통     150,880
101  경기    수원 장안     107,347
102  경기    수원 팔달      76,726
103  경기       시흥     261,394
104  경기    안산 단원     165,736
105  경기    안산 상록     149,567
106  경기       안성     112,090
107  경기    안양 동안     123,733
108  경기    안양 만안      88,643
109  경기       양주     114,944
110  경기       양평      64,065
111  경기       여주      71,807
112  경기       연천      29,479
113  경기       오산     112,258
114  경기    용인 기흥     196,947
115  경기    용인 수지     148,793
116  경기    용인 처인     142,619
117  경기       의왕      69,082
118  경기      의정부     172,149
119  경기       이천     122,790
120  경기       파주     233,754
121  경기       평택     309,131
122  경기       포천      98,262
123  경기       하남     134,572
124  경기       화성     475,924
125  경기        계   6,172,022
126  강원       강릉     114,677
127  강원       고성      15,269
128  강원       동해      47,787
129  강원       삼척      33,483
130  강원       속초      40,549
131  강원       양구      12,442
132  강원       양양      16,636
133  강원       영월      22,039
134  강원       원주     184,141
135  강원       인제      19,394
136  강원       정선      21,477
137  강원       철원      24,814
138  강원       춘천     142,226
139  강원       태백      20,821
140  강원       평창      26,493
141  강원       홍천      40,722
142  강원       화천      13,550
143  강원       횡성      28,081
144  강원        계     824,601
145  충북       괴산      23,507
146  충북       단양      16,629
147  충북       보은      19,409
148  충북       영동      25,579
149  충북       옥천      28,864
150  충북       음성      61,100
151  충북       제천      71,360
152  충북       증평      20,156
153  충북       진천      52,368
154  충북       청원          20
155  충북    청주 상당      96,603
156  충북    청주 서원     106,419
157  충북    청주 청원     108,824
158  충북    청주 흥덕     139,764
159  충북       충주     118,935
160  충북        계     889,537
161  충남       계룡      23,253
162  충남       공주      57,169
163  충남       금산      30,934
164  충남       논산      63,884
165  충남       당진     101,049
166  충남       보령      54,380
167  충남       부여      35,791
168  충남       서산     100,543
169  충남       서천      28,152
170  충남       아산     180,809
171  충남       예산      45,119
172  충남    천안 동남     137,275
173  충남    천안 서북     204,817
174  충남       청양      18,008
175  충남       태안      35,164
176  충남       홍성      55,246
177  충남        계   1,171,593
178  전북       고창      31,491
179  전북       군산     138,743
180  전북       김제      47,860
181  전북       남원      45,299
182  전북       무주      13,527
183  전북       부안      28,267
184  전북       순창      15,027
185  전북       완주      55,615
186  전북       익산     143,138
187  전북       임실      14,873
188  전북       장수      12,633
189  전북    전주 덕진     180,598
190  전북    전주 완산     157,354
191  전북       정읍      58,829
192  전북       진안      14,596
193  전북        계     957,850
194  전남       강진      19,980
195  전남       고흥      33,209
196  전남       곡성      15,820
197  전남       광양      90,309
198  전남       구례      14,033
199  전남       나주      69,579
200  전남       담양      29,299
201  전남       목포     100,383
202  전남       무안      51,055
203  전남       보성      35,265
204  전남       순천     147,555
205  전남       신안     100,689
206  전남       여수     139,779
207  전남       영광      28,919
208  전남       영암      36,401
209  전남       완도      26,297
210  전남       장성      28,139
211  전남       장흥      20,782
212  전남       진도      17,523
213  전남       함평      49,753
214  전남       해남      70,495
215  전남       화순      35,545
216  전남        계   1,160,809
217  경북       경산     144,466
218  경북       경주     147,420
219  경북       고령      21,284
220  경북       구미     221,876
221  경북       군위      15,336
222  경북       김천      77,457
223  경북       문경      38,271
224  경북       봉화      18,494
225  경북       상주      55,309
226  경북       성주      32,265
227  경북       안동      86,301
228  경북       영덕      19,551
229  경북       영양      10,095
230  경북       영주      57,463
231  경북       영천      63,005
232  경북       예천      31,254
233  경북       울릉       5,946
234  경북       울진      26,996
235  경북       의성      32,335
236  경북       청도      26,068
237  경북       청송      16,212
238  경북       칠곡      71,509
239  경북     포항 남     130,961
240  경북     포항 북     145,091
241  경북        계   1,494,965
242  경남       거제     108,939
243  경남       거창      33,598
244  경남       고성      27,309
245  경남       김해     284,617
246  경남       남해      20,773
247  경남       밀양      60,453
248  경남       사천      58,517
249  경남       산청      21,396
250  경남       양산     178,813
251  경남       의령      15,662
252  경남       진주     174,010
253  경남       창녕      36,586
254  경남  창원 마산합포      98,848
255  경남  창원 마산회원     101,587
256  경남    창원 성산     200,206
257  경남    창원 의창     120,323
258  경남    창원 진해      95,316
259  경남       통영      54,182
260  경남       하동      24,587
261  경남       함안      64,756
262  경남       함양      20,244
263  경남       합천      24,342
264  경남        계   1,825,064
265  제주      서귀포     107,598
266  제주       제주     544,015
267  제주        계     651,613
268  합계      NaN  24,810,637

In [63]:
df["시군구"] = df["시"].map(str) + " " + df["군구"]

In [64]:
df = df.loc[df['군구'] != '계']
df

      시       군구   자동차 등록 현황         시군구
0    서울       강남     238,244       서울 강남
1    서울       강동     152,372       서울 강동
2    서울       강북      75,389       서울 강북
3    서울       강서     204,285       서울 강서
4    서울       관악     118,529       서울 관악
5    서울       광진      98,364       서울 광진
6    서울       구로     145,204       서울 구로
7    서울       금천      89,891       서울 금천
8    서울       노원     152,145       서울 노원
9    서울       도봉      95,745       서울 도봉
10   서울      동대문      98,427      서울 동대문
11   서울       동작     106,156       서울 동작
12   서울       마포     121,224       서울 마포
13   서울      서대문      89,451      서울 서대문
14   서울       서초     177,928       서울 서초
15   서울       성동     106,348       서울 성동
16   서울       성북     121,263       서울 성북
17   서울       송파     246,647       서울 송파
18   서울       양천     151,317       서울 양천
19   서울      영등포     146,188      서울 영등포
20   서울       용산      79,619       서울 용산
21   서울       은평     132,712       서울 은평
22   서울       종로      50,258       서울 종로
23   서울        중      61,930        서울 중
24   서울       중랑     114,325       서울 중랑
26   부산       강서      85,620       부산 강서
27   부산       금정      88,347       부산 금정
28   부산       기장      83,626       부산 기장
29   부산        남     100,847        부산 남
30   부산        동      57,009        부산 동
31   부산       동래      96,440       부산 동래
32   부산      부산진     143,182      부산 부산진
33   부산        북     106,063        부산 북
34   부산       사상      89,145       부산 사상
35   부산       사하     113,846       부산 사하
36   부산        서      30,681        부산 서
37   부산       수영     104,965       부산 수영
38   부산       연제     104,488       부산 연제
39   부산       영도      33,470       부산 영도
40   부산        중      37,426        부산 중
41   부산      해운대     181,829      부산 해운대
43   대구        남      57,794        대구 남
44   대구       달서     286,275       대구 달서
45   대구       달성     141,955       대구 달성
46   대구        동     166,008        대구 동
47   대구        북     210,306        대구 북
48   대구        서      72,207        대구 서
49   대구       수성     214,023       대구 수성
50   대구        중      61,368        대구 중
52   인천       강화      53,600       인천 강화
53   인천       계양     304,413       인천 계양
54   인천       남동     306,100       인천 남동
55   인천        동      27,486        인천 동
56   인천      미추홀     169,090      인천 미추홀
57   인천       부평     249,518       인천 부평
58   인천        서     258,220        인천 서
59   인천       연수     208,286       인천 연수
60   인천       옹진      12,686       인천 옹진
61   인천        중      80,045        인천 중
63   광주       광산     210,391       광주 광산
64   광주        남      94,984        광주 남
65   광주        동      45,031        광주 동
66   광주        북     200,103        광주 북
67   광주        서     147,924        광주 서
69   대전       대덕      93,017       대전 대덕
70   대전        동      96,524        대전 동
71   대전        서     215,663        대전 서
72   대전       유성     183,762       대전 유성
73   대전        중     102,115        대전 중
75   울산        남     161,974        울산 남
76   울산        동      63,179        울산 동
77   울산        북     119,296        울산 북
78   울산       울주     132,244       울산 울주
79   울산        중     103,132        울산 중
81   세종   세종특별자치     182,919   세종 세종특별자치
83   경기       가평      32,295       경기 가평
84   경기    고양 덕양     188,121    경기 고양 덕양
85   경기   고양 일산동     131,845   경기 고양 일산동
86   경기   고양 일산서     121,238   경기 고양 일산서
87   경기       과천      27,306       경기 과천
88   경기       광명     105,277       경기 광명
89   경기       광주     204,116       경기 광주
90   경기       구리      73,443       경기 구리
91   경기       군포     103,749       경기 군포
92   경기       김포     237,235       경기 김포
93   경기      남양주     315,280      경기 남양주
94   경기      동두천      40,140      경기 동두천
95   경기       부천     308,449       경기 부천
96   경기    성남 분당     194,196    경기 성남 분당
97   경기    성남 수정      79,981    경기 성남 수정
98   경기    성남 중원      75,968    경기 성남 중원
99   경기    수원 권선     200,691    경기 수원 권선
100  경기    수원 영통     150,880    경기 수원 영통
101  경기    수원 장안     107,347    경기 수원 장안
102  경기    수원 팔달      76,726    경기 수원 팔달
103  경기       시흥     261,394       경기 시흥
104  경기    안산 단원     165,736    경기 안산 단원
105  경기    안산 상록     149,567    경기 안산 상록
106  경기       안성     112,090       경기 안성
107  경기    안양 동안     123,733    경기 안양 동안
108  경기    안양 만안      88,643    경기 안양 만안
109  경기       양주     114,944       경기 양주
110  경기       양평      64,065       경기 양평
111  경기       여주      71,807       경기 여주
112  경기       연천      29,479       경기 연천
113  경기       오산     112,258       경기 오산
114  경기    용인 기흥     196,947    경기 용인 기흥
115  경기    용인 수지     148,793    경기 용인 수지
116  경기    용인 처인     142,619    경기 용인 처인
117  경기       의왕      69,082       경기 의왕
118  경기      의정부     172,149      경기 의정부
119  경기       이천     122,790       경기 이천
120  경기       파주     233,754       경기 파주
121  경기       평택     309,131       경기 평택
122  경기       포천      98,262       경기 포천
123  경기       하남     134,572       경기 하남
124  경기       화성     475,924       경기 화성
126  강원       강릉     114,677       강원 강릉
127  강원       고성      15,269       강원 고성
128  강원       동해      47,787       강원 동해
129  강원       삼척      33,483       강원 삼척
130  강원       속초      40,549       강원 속초
131  강원       양구      12,442       강원 양구
132  강원       양양      16,636       강원 양양
133  강원       영월      22,039       강원 영월
134  강원       원주     184,141       강원 원주
135  강원       인제      19,394       강원 인제
136  강원       정선      21,477       강원 정선
137  강원       철원      24,814       강원 철원
138  강원       춘천     142,226       강원 춘천
139  강원       태백      20,821       강원 태백
140  강원       평창      26,493       강원 평창
141  강원       홍천      40,722       강원 홍천
142  강원       화천      13,550       강원 화천
143  강원       횡성      28,081       강원 횡성
145  충북       괴산      23,507       충북 괴산
146  충북       단양      16,629       충북 단양
147  충북       보은      19,409       충북 보은
148  충북       영동      25,579       충북 영동
149  충북       옥천      28,864       충북 옥천
150  충북       음성      61,100       충북 음성
151  충북       제천      71,360       충북 제천
152  충북       증평      20,156       충북 증평
153  충북       진천      52,368       충북 진천
154  충북       청원          20       충북 청원
155  충북    청주 상당      96,603    충북 청주 상당
156  충북    청주 서원     106,419    충북 청주 서원
157  충북    청주 청원     108,824    충북 청주 청원
158  충북    청주 흥덕     139,764    충북 청주 흥덕
159  충북       충주     118,935       충북 충주
161  충남       계룡      23,253       충남 계룡
162  충남       공주      57,169       충남 공주
163  충남       금산      30,934       충남 금산
164  충남       논산      63,884       충남 논산
165  충남       당진     101,049       충남 당진
166  충남       보령      54,380       충남 보령
167  충남       부여      35,791       충남 부여
168  충남       서산     100,543       충남 서산
169  충남       서천      28,152       충남 서천
170  충남       아산     180,809       충남 아산
171  충남       예산      45,119       충남 예산
172  충남    천안 동남     137,275    충남 천안 동남
173  충남    천안 서북     204,817    충남 천안 서북
174  충남       청양      18,008       충남 청양
175  충남       태안      35,164       충남 태안
176  충남       홍성      55,246       충남 홍성
178  전북       고창      31,491       전북 고창
179  전북       군산     138,743       전북 군산
180  전북       김제      47,860       전북 김제
181  전북       남원      45,299       전북 남원
182  전북       무주      13,527       전북 무주
183  전북       부안      28,267       전북 부안
184  전북       순창      15,027       전북 순창
185  전북       완주      55,615       전북 완주
186  전북       익산     143,138       전북 익산
187  전북       임실      14,873       전북 임실
188  전북       장수      12,633       전북 장수
189  전북    전주 덕진     180,598    전북 전주 덕진
190  전북    전주 완산     157,354    전북 전주 완산
191  전북       정읍      58,829       전북 정읍
192  전북       진안      14,596       전북 진안
194  전남       강진      19,980       전남 강진
195  전남       고흥      33,209       전남 고흥
196  전남       곡성      15,820       전남 곡성
197  전남       광양      90,309       전남 광양
198  전남       구례      14,033       전남 구례
199  전남       나주      69,579       전남 나주
200  전남       담양      29,299       전남 담양
201  전남       목포     100,383       전남 목포
202  전남       무안      51,055       전남 무안
203  전남       보성      35,265       전남 보성
204  전남       순천     147,555       전남 순천
205  전남       신안     100,689       전남 신안
206  전남       여수     139,779       전남 여수
207  전남       영광      28,919       전남 영광
208  전남       영암      36,401       전남 영암
209  전남       완도      26,297       전남 완도
210  전남       장성      28,139       전남 장성
211  전남       장흥      20,782       전남 장흥
212  전남       진도      17,523       전남 진도
213  전남       함평      49,753       전남 함평
214  전남       해남      70,495       전남 해남
215  전남       화순      35,545       전남 화순
217  경북       경산     144,466       경북 경산
218  경북       경주     147,420       경북 경주
219  경북       고령      21,284       경북 고령
220  경북       구미     221,876       경북 구미
221  경북       군위      15,336       경북 군위
222  경북       김천      77,457       경북 김천
223  경북       문경      38,271       경북 문경
224  경북       봉화      18,494       경북 봉화
225  경북       상주      55,309       경북 상주
226  경북       성주      32,265       경북 성주
227  경북       안동      86,301       경북 안동
228  경북       영덕      19,551       경북 영덕
229  경북       영양      10,095       경북 영양
230  경북       영주      57,463       경북 영주
231  경북       영천      63,005       경북 영천
232  경북       예천      31,254       경북 예천
233  경북       울릉       5,946       경북 울릉
234  경북       울진      26,996       경북 울진
235  경북       의성      32,335       경북 의성
236  경북       청도      26,068       경북 청도
237  경북       청송      16,212       경북 청송
238  경북       칠곡      71,509       경북 칠곡
239  경북     포항 남     130,961     경북 포항 남
240  경북     포항 북     145,091     경북 포항 북
242  경남       거제     108,939       경남 거제
243  경남       거창      33,598       경남 거창
244  경남       고성      27,309       경남 고성
245  경남       김해     284,617       경남 김해
246  경남       남해      20,773       경남 남해
247  경남       밀양      60,453       경남 밀양
248  경남       사천      58,517       경남 사천
249  경남       산청      21,396       경남 산청
250  경남       양산     178,813       경남 양산
251  경남       의령      15,662       경남 의령
252  경남       진주     174,010       경남 진주
253  경남       창녕      36,586       경남 창녕
254  경남  창원 마산합포      98,848  경남 창원 마산합포
255  경남  창원 마산회원     101,587  경남 창원 마산회원
256  경남    창원 성산     200,206    경남 창원 성산
257  경남    창원 의창     120,323    경남 창원 의창
258  경남    창원 진해      95,316    경남 창원 진해
259  경남       통영      54,182       경남 통영
260  경남       하동      24,587       경남 하동
261  경남       함안      64,756       경남 함안
262  경남       함양      20,244       경남 함양
263  경남       합천      24,342       경남 합천
265  제주      서귀포     107,598      제주 서귀포
266  제주       제주     544,015       제주 제주
268  합계      NaN  24,810,637         NaN

In [65]:
df = df1.loc[df['시'] != '합계' ]
df

      시       군구 자동차 등록 현황         시군구
0    서울       강남   238,244       서울 강남
1    서울       강동   152,372       서울 강동
2    서울       강북    75,389       서울 강북
3    서울       강서   204,285       서울 강서
4    서울       관악   118,529       서울 관악
5    서울       광진    98,364       서울 광진
6    서울       구로   145,204       서울 구로
7    서울       금천    89,891       서울 금천
8    서울       노원   152,145       서울 노원
9    서울       도봉    95,745       서울 도봉
10   서울      동대문    98,427      서울 동대문
11   서울       동작   106,156       서울 동작
12   서울       마포   121,224       서울 마포
13   서울      서대문    89,451      서울 서대문
14   서울       서초   177,928       서울 서초
15   서울       성동   106,348       서울 성동
16   서울       성북   121,263       서울 성북
17   서울       송파   246,647       서울 송파
18   서울       양천   151,317       서울 양천
19   서울      영등포   146,188      서울 영등포
20   서울       용산    79,619       서울 용산
21   서울       은평   132,712       서울 은평
22   서울       종로    50,258       서울 종로
23   서울        중    61,930        서울 중
24   서울       중랑   114,325       서울 중랑
26   부산       강서    85,620       부산 강서
27   부산       금정    88,347       부산 금정
28   부산       기장    83,626       부산 기장
29   부산        남   100,847        부산 남
30   부산        동    57,009        부산 동
31   부산       동래    96,440       부산 동래
32   부산      부산진   143,182      부산 부산진
33   부산        북   106,063        부산 북
34   부산       사상    89,145       부산 사상
35   부산       사하   113,846       부산 사하
36   부산        서    30,681        부산 서
37   부산       수영   104,965       부산 수영
38   부산       연제   104,488       부산 연제
39   부산       영도    33,470       부산 영도
40   부산        중    37,426        부산 중
41   부산      해운대   181,829      부산 해운대
43   대구        남    57,794        대구 남
44   대구       달서   286,275       대구 달서
45   대구       달성   141,955       대구 달성
46   대구        동   166,008        대구 동
47   대구        북   210,306        대구 북
48   대구        서    72,207        대구 서
49   대구       수성   214,023       대구 수성
50   대구        중    61,368        대구 중
52   인천       강화    53,600       인천 강화
53   인천       계양   304,413       인천 계양
54   인천       남동   306,100       인천 남동
55   인천        동    27,486        인천 동
56   인천      미추홀   169,090      인천 미추홀
57   인천       부평   249,518       인천 부평
58   인천        서   258,220        인천 서
59   인천       연수   208,286       인천 연수
60   인천       옹진    12,686       인천 옹진
61   인천        중    80,045        인천 중
63   광주       광산   210,391       광주 광산
64   광주        남    94,984        광주 남
65   광주        동    45,031        광주 동
66   광주        북   200,103        광주 북
67   광주        서   147,924        광주 서
69   대전       대덕    93,017       대전 대덕
70   대전        동    96,524        대전 동
71   대전        서   215,663        대전 서
72   대전       유성   183,762       대전 유성
73   대전        중   102,115        대전 중
75   울산        남   161,974        울산 남
76   울산        동    63,179        울산 동
77   울산        북   119,296        울산 북
78   울산       울주   132,244       울산 울주
79   울산        중   103,132        울산 중
81   세종   세종특별자치   182,919   세종 세종특별자치
83   경기       가평    32,295       경기 가평
84   경기    고양 덕양   188,121    경기 고양 덕양
85   경기   고양 일산동   131,845   경기 고양 일산동
86   경기   고양 일산서   121,238   경기 고양 일산서
87   경기       과천    27,306       경기 과천
88   경기       광명   105,277       경기 광명
89   경기       광주   204,116       경기 광주
90   경기       구리    73,443       경기 구리
91   경기       군포   103,749       경기 군포
92   경기       김포   237,235       경기 김포
93   경기      남양주   315,280      경기 남양주
94   경기      동두천    40,140      경기 동두천
95   경기       부천   308,449       경기 부천
96   경기    성남 분당   194,196    경기 성남 분당
97   경기    성남 수정    79,981    경기 성남 수정
98   경기    성남 중원    75,968    경기 성남 중원
99   경기    수원 권선   200,691    경기 수원 권선
100  경기    수원 영통   150,880    경기 수원 영통
101  경기    수원 장안   107,347    경기 수원 장안
102  경기    수원 팔달    76,726    경기 수원 팔달
103  경기       시흥   261,394       경기 시흥
104  경기    안산 단원   165,736    경기 안산 단원
105  경기    안산 상록   149,567    경기 안산 상록
106  경기       안성   112,090       경기 안성
107  경기    안양 동안   123,733    경기 안양 동안
108  경기    안양 만안    88,643    경기 안양 만안
109  경기       양주   114,944       경기 양주
110  경기       양평    64,065       경기 양평
111  경기       여주    71,807       경기 여주
112  경기       연천    29,479       경기 연천
113  경기       오산   112,258       경기 오산
114  경기    용인 기흥   196,947    경기 용인 기흥
115  경기    용인 수지   148,793    경기 용인 수지
116  경기    용인 처인   142,619    경기 용인 처인
117  경기       의왕    69,082       경기 의왕
118  경기      의정부   172,149      경기 의정부
119  경기       이천   122,790       경기 이천
120  경기       파주   233,754       경기 파주
121  경기       평택   309,131       경기 평택
122  경기       포천    98,262       경기 포천
123  경기       하남   134,572       경기 하남
124  경기       화성   475,924       경기 화성
126  강원       강릉   114,677       강원 강릉
127  강원       고성    15,269       강원 고성
128  강원       동해    47,787       강원 동해
129  강원       삼척    33,483       강원 삼척
130  강원       속초    40,549       강원 속초
131  강원       양구    12,442       강원 양구
132  강원       양양    16,636       강원 양양
133  강원       영월    22,039       강원 영월
134  강원       원주   184,141       강원 원주
135  강원       인제    19,394       강원 인제
136  강원       정선    21,477       강원 정선
137  강원       철원    24,814       강원 철원
138  강원       춘천   142,226       강원 춘천
139  강원       태백    20,821       강원 태백
140  강원       평창    26,493       강원 평창
141  강원       홍천    40,722       강원 홍천
142  강원       화천    13,550       강원 화천
143  강원       횡성    28,081       강원 횡성
145  충북       괴산    23,507       충북 괴산
146  충북       단양    16,629       충북 단양
147  충북       보은    19,409       충북 보은
148  충북       영동    25,579       충북 영동
149  충북       옥천    28,864       충북 옥천
150  충북       음성    61,100       충북 음성
151  충북       제천    71,360       충북 제천
152  충북       증평    20,156       충북 증평
153  충북       진천    52,368       충북 진천
154  충북       청원        20       충북 청원
155  충북    청주 상당    96,603    충북 청주 상당
156  충북    청주 서원   106,419    충북 청주 서원
157  충북    청주 청원   108,824    충북 청주 청원
158  충북    청주 흥덕   139,764    충북 청주 흥덕
159  충북       충주   118,935       충북 충주
161  충남       계룡    23,253       충남 계룡
162  충남       공주    57,169       충남 공주
163  충남       금산    30,934       충남 금산
164  충남       논산    63,884       충남 논산
165  충남       당진   101,049       충남 당진
166  충남       보령    54,380       충남 보령
167  충남       부여    35,791       충남 부여
168  충남       서산   100,543       충남 서산
169  충남       서천    28,152       충남 서천
170  충남       아산   180,809       충남 아산
171  충남       예산    45,119       충남 예산
172  충남    천안 동남   137,275    충남 천안 동남
173  충남    천안 서북   204,817    충남 천안 서북
174  충남       청양    18,008       충남 청양
175  충남       태안    35,164       충남 태안
176  충남       홍성    55,246       충남 홍성
178  전북       고창    31,491       전북 고창
179  전북       군산   138,743       전북 군산
180  전북       김제    47,860       전북 김제
181  전북       남원    45,299       전북 남원
182  전북       무주    13,527       전북 무주
183  전북       부안    28,267       전북 부안
184  전북       순창    15,027       전북 순창
185  전북       완주    55,615       전북 완주
186  전북       익산   143,138       전북 익산
187  전북       임실    14,873       전북 임실
188  전북       장수    12,633       전북 장수
189  전북    전주 덕진   180,598    전북 전주 덕진
190  전북    전주 완산   157,354    전북 전주 완산
191  전북       정읍    58,829       전북 정읍
192  전북       진안    14,596       전북 진안
194  전남       강진    19,980       전남 강진
195  전남       고흥    33,209       전남 고흥
196  전남       곡성    15,820       전남 곡성
197  전남       광양    90,309       전남 광양
198  전남       구례    14,033       전남 구례
199  전남       나주    69,579       전남 나주
200  전남       담양    29,299       전남 담양
201  전남       목포   100,383       전남 목포
202  전남       무안    51,055       전남 무안
203  전남       보성    35,265       전남 보성
204  전남       순천   147,555       전남 순천
205  전남       신안   100,689       전남 신안
206  전남       여수   139,779       전남 여수
207  전남       영광    28,919       전남 영광
208  전남       영암    36,401       전남 영암
209  전남       완도    26,297       전남 완도
210  전남       장성    28,139       전남 장성
211  전남       장흥    20,782       전남 장흥
212  전남       진도    17,523       전남 진도
213  전남       함평    49,753       전남 함평
214  전남       해남    70,495       전남 해남
215  전남       화순    35,545       전남 화순
217  경북       경산   144,466       경북 경산
218  경북       경주   147,420       경북 경주
219  경북       고령    21,284       경북 고령
220  경북       구미   221,876       경북 구미
221  경북       군위    15,336       경북 군위
222  경북       김천    77,457       경북 김천
223  경북       문경    38,271       경북 문경
224  경북       봉화    18,494       경북 봉화
225  경북       상주    55,309       경북 상주
226  경북       성주    32,265       경북 성주
227  경북       안동    86,301       경북 안동
228  경북       영덕    19,551       경북 영덕
229  경북       영양    10,095       경북 영양
230  경북       영주    57,463       경북 영주
231  경북       영천    63,005       경북 영천
232  경북       예천    31,254       경북 예천
233  경북       울릉     5,946       경북 울릉
234  경북       울진    26,996       경북 울진
235  경북       의성    32,335       경북 의성
236  경북       청도    26,068       경북 청도
237  경북       청송    16,212       경북 청송
238  경북       칠곡    71,509       경북 칠곡
239  경북     포항 남   130,961     경북 포항 남
240  경북     포항 북   145,091     경북 포항 북
242  경남       거제   108,939       경남 거제
243  경남       거창    33,598       경남 거창
244  경남       고성    27,309       경남 고성
245  경남       김해   284,617       경남 김해
246  경남       남해    20,773       경남 남해
247  경남       밀양    60,453       경남 밀양
248  경남       사천    58,517       경남 사천
249  경남       산청    21,396       경남 산청
250  경남       양산   178,813       경남 양산
251  경남       의령    15,662       경남 의령
252  경남       진주   174,010       경남 진주
253  경남       창녕    36,586       경남 창녕
254  경남  창원 마산합포    98,848  경남 창원 마산합포
255  경남  창원 마산회원   101,587  경남 창원 마산회원
256  경남    창원 성산   200,206    경남 창원 성산
257  경남    창원 의창   120,323    경남 창원 의창
258  경남    창원 진해    95,316    경남 창원 진해
259  경남       통영    54,182       경남 통영
260  경남       하동    24,587       경남 하동
261  경남       함안    64,756       경남 함안
262  경남       함양    20,244       경남 함양
263  경남       합천    24,342       경남 합천
265  제주      서귀포   107,598      제주 서귀포
266  제주       제주   544,015       제주 제주

In [66]:
df.columns.tolist()

['시', '군구', '자동차 등록 현황', '시군구']

In [67]:
df = df[['시군구', '시', '군구', '자동차 등록 현황']]
df

            시군구   시       군구 자동차 등록 현황
0         서울 강남  서울       강남   238,244
1         서울 강동  서울       강동   152,372
2         서울 강북  서울       강북    75,389
3         서울 강서  서울       강서   204,285
4         서울 관악  서울       관악   118,529
5         서울 광진  서울       광진    98,364
6         서울 구로  서울       구로   145,204
7         서울 금천  서울       금천    89,891
8         서울 노원  서울       노원   152,145
9         서울 도봉  서울       도봉    95,745
10       서울 동대문  서울      동대문    98,427
11        서울 동작  서울       동작   106,156
12        서울 마포  서울       마포   121,224
13       서울 서대문  서울      서대문    89,451
14        서울 서초  서울       서초   177,928
15        서울 성동  서울       성동   106,348
16        서울 성북  서울       성북   121,263
17        서울 송파  서울       송파   246,647
18        서울 양천  서울       양천   151,317
19       서울 영등포  서울      영등포   146,188
20        서울 용산  서울       용산    79,619
21        서울 은평  서울       은평   132,712
22        서울 종로  서울       종로    50,258
23         서울 중  서울        중    61,930
24        서울 중랑  서울       중랑   114,325
26        부산 강서  부산       강서    85,620
27        부산 금정  부산       금정    88,347
28        부산 기장  부산       기장    83,626
29         부산 남  부산        남   100,847
30         부산 동  부산        동    57,009
31        부산 동래  부산       동래    96,440
32       부산 부산진  부산      부산진   143,182
33         부산 북  부산        북   106,063
34        부산 사상  부산       사상    89,145
35        부산 사하  부산       사하   113,846
36         부산 서  부산        서    30,681
37        부산 수영  부산       수영   104,965
38        부산 연제  부산       연제   104,488
39        부산 영도  부산       영도    33,470
40         부산 중  부산        중    37,426
41       부산 해운대  부산      해운대   181,829
43         대구 남  대구        남    57,794
44        대구 달서  대구       달서   286,275
45        대구 달성  대구       달성   141,955
46         대구 동  대구        동   166,008
47         대구 북  대구        북   210,306
48         대구 서  대구        서    72,207
49        대구 수성  대구       수성   214,023
50         대구 중  대구        중    61,368
52        인천 강화  인천       강화    53,600
53        인천 계양  인천       계양   304,413
54        인천 남동  인천       남동   306,100
55         인천 동  인천        동    27,486
56       인천 미추홀  인천      미추홀   169,090
57        인천 부평  인천       부평   249,518
58         인천 서  인천        서   258,220
59        인천 연수  인천       연수   208,286
60        인천 옹진  인천       옹진    12,686
61         인천 중  인천        중    80,045
63        광주 광산  광주       광산   210,391
64         광주 남  광주        남    94,984
65         광주 동  광주        동    45,031
66         광주 북  광주        북   200,103
67         광주 서  광주        서   147,924
69        대전 대덕  대전       대덕    93,017
70         대전 동  대전        동    96,524
71         대전 서  대전        서   215,663
72        대전 유성  대전       유성   183,762
73         대전 중  대전        중   102,115
75         울산 남  울산        남   161,974
76         울산 동  울산        동    63,179
77         울산 북  울산        북   119,296
78        울산 울주  울산       울주   132,244
79         울산 중  울산        중   103,132
81    세종 세종특별자치  세종   세종특별자치   182,919
83        경기 가평  경기       가평    32,295
84     경기 고양 덕양  경기    고양 덕양   188,121
85    경기 고양 일산동  경기   고양 일산동   131,845
86    경기 고양 일산서  경기   고양 일산서   121,238
87        경기 과천  경기       과천    27,306
88        경기 광명  경기       광명   105,277
89        경기 광주  경기       광주   204,116
90        경기 구리  경기       구리    73,443
91        경기 군포  경기       군포   103,749
92        경기 김포  경기       김포   237,235
93       경기 남양주  경기      남양주   315,280
94       경기 동두천  경기      동두천    40,140
95        경기 부천  경기       부천   308,449
96     경기 성남 분당  경기    성남 분당   194,196
97     경기 성남 수정  경기    성남 수정    79,981
98     경기 성남 중원  경기    성남 중원    75,968
99     경기 수원 권선  경기    수원 권선   200,691
100    경기 수원 영통  경기    수원 영통   150,880
101    경기 수원 장안  경기    수원 장안   107,347
102    경기 수원 팔달  경기    수원 팔달    76,726
103       경기 시흥  경기       시흥   261,394
104    경기 안산 단원  경기    안산 단원   165,736
105    경기 안산 상록  경기    안산 상록   149,567
106       경기 안성  경기       안성   112,090
107    경기 안양 동안  경기    안양 동안   123,733
108    경기 안양 만안  경기    안양 만안    88,643
109       경기 양주  경기       양주   114,944
110       경기 양평  경기       양평    64,065
111       경기 여주  경기       여주    71,807
112       경기 연천  경기       연천    29,479
113       경기 오산  경기       오산   112,258
114    경기 용인 기흥  경기    용인 기흥   196,947
115    경기 용인 수지  경기    용인 수지   148,793
116    경기 용인 처인  경기    용인 처인   142,619
117       경기 의왕  경기       의왕    69,082
118      경기 의정부  경기      의정부   172,149
119       경기 이천  경기       이천   122,790
120       경기 파주  경기       파주   233,754
121       경기 평택  경기       평택   309,131
122       경기 포천  경기       포천    98,262
123       경기 하남  경기       하남   134,572
124       경기 화성  경기       화성   475,924
126       강원 강릉  강원       강릉   114,677
127       강원 고성  강원       고성    15,269
128       강원 동해  강원       동해    47,787
129       강원 삼척  강원       삼척    33,483
130       강원 속초  강원       속초    40,549
131       강원 양구  강원       양구    12,442
132       강원 양양  강원       양양    16,636
133       강원 영월  강원       영월    22,039
134       강원 원주  강원       원주   184,141
135       강원 인제  강원       인제    19,394
136       강원 정선  강원       정선    21,477
137       강원 철원  강원       철원    24,814
138       강원 춘천  강원       춘천   142,226
139       강원 태백  강원       태백    20,821
140       강원 평창  강원       평창    26,493
141       강원 홍천  강원       홍천    40,722
142       강원 화천  강원       화천    13,550
143       강원 횡성  강원       횡성    28,081
145       충북 괴산  충북       괴산    23,507
146       충북 단양  충북       단양    16,629
147       충북 보은  충북       보은    19,409
148       충북 영동  충북       영동    25,579
149       충북 옥천  충북       옥천    28,864
150       충북 음성  충북       음성    61,100
151       충북 제천  충북       제천    71,360
152       충북 증평  충북       증평    20,156
153       충북 진천  충북       진천    52,368
154       충북 청원  충북       청원        20
155    충북 청주 상당  충북    청주 상당    96,603
156    충북 청주 서원  충북    청주 서원   106,419
157    충북 청주 청원  충북    청주 청원   108,824
158    충북 청주 흥덕  충북    청주 흥덕   139,764
159       충북 충주  충북       충주   118,935
161       충남 계룡  충남       계룡    23,253
162       충남 공주  충남       공주    57,169
163       충남 금산  충남       금산    30,934
164       충남 논산  충남       논산    63,884
165       충남 당진  충남       당진   101,049
166       충남 보령  충남       보령    54,380
167       충남 부여  충남       부여    35,791
168       충남 서산  충남       서산   100,543
169       충남 서천  충남       서천    28,152
170       충남 아산  충남       아산   180,809
171       충남 예산  충남       예산    45,119
172    충남 천안 동남  충남    천안 동남   137,275
173    충남 천안 서북  충남    천안 서북   204,817
174       충남 청양  충남       청양    18,008
175       충남 태안  충남       태안    35,164
176       충남 홍성  충남       홍성    55,246
178       전북 고창  전북       고창    31,491
179       전북 군산  전북       군산   138,743
180       전북 김제  전북       김제    47,860
181       전북 남원  전북       남원    45,299
182       전북 무주  전북       무주    13,527
183       전북 부안  전북       부안    28,267
184       전북 순창  전북       순창    15,027
185       전북 완주  전북       완주    55,615
186       전북 익산  전북       익산   143,138
187       전북 임실  전북       임실    14,873
188       전북 장수  전북       장수    12,633
189    전북 전주 덕진  전북    전주 덕진   180,598
190    전북 전주 완산  전북    전주 완산   157,354
191       전북 정읍  전북       정읍    58,829
192       전북 진안  전북       진안    14,596
194       전남 강진  전남       강진    19,980
195       전남 고흥  전남       고흥    33,209
196       전남 곡성  전남       곡성    15,820
197       전남 광양  전남       광양    90,309
198       전남 구례  전남       구례    14,033
199       전남 나주  전남       나주    69,579
200       전남 담양  전남       담양    29,299
201       전남 목포  전남       목포   100,383
202       전남 무안  전남       무안    51,055
203       전남 보성  전남       보성    35,265
204       전남 순천  전남       순천   147,555
205       전남 신안  전남       신안   100,689
206       전남 여수  전남       여수   139,779
207       전남 영광  전남       영광    28,919
208       전남 영암  전남       영암    36,401
209       전남 완도  전남       완도    26,297
210       전남 장성  전남       장성    28,139
211       전남 장흥  전남       장흥    20,782
212       전남 진도  전남       진도    17,523
213       전남 함평  전남       함평    49,753
214       전남 해남  전남       해남    70,495
215       전남 화순  전남       화순    35,545
217       경북 경산  경북       경산   144,466
218       경북 경주  경북       경주   147,420
219       경북 고령  경북       고령    21,284
220       경북 구미  경북       구미   221,876
221       경북 군위  경북       군위    15,336
222       경북 김천  경북       김천    77,457
223       경북 문경  경북       문경    38,271
224       경북 봉화  경북       봉화    18,494
225       경북 상주  경북       상주    55,309
226       경북 성주  경북       성주    32,265
227       경북 안동  경북       안동    86,301
228       경북 영덕  경북       영덕    19,551
229       경북 영양  경북       영양    10,095
230       경북 영주  경북       영주    57,463
231       경북 영천  경북       영천    63,005
232       경북 예천  경북       예천    31,254
233       경북 울릉  경북       울릉     5,946
234       경북 울진  경북       울진    26,996
235       경북 의성  경북       의성    32,335
236       경북 청도  경북       청도    26,068
237       경북 청송  경북       청송    16,212
238       경북 칠곡  경북       칠곡    71,509
239     경북 포항 남  경북     포항 남   130,961
240     경북 포항 북  경북     포항 북   145,091
242       경남 거제  경남       거제   108,939
243       경남 거창  경남       거창    33,598
244       경남 고성  경남       고성    27,309
245       경남 김해  경남       김해   284,617
246       경남 남해  경남       남해    20,773
247       경남 밀양  경남       밀양    60,453
248       경남 사천  경남       사천    58,517
249       경남 산청  경남       산청    21,396
250       경남 양산  경남       양산   178,813
251       경남 의령  경남       의령    15,662
252       경남 진주  경남       진주   174,010
253       경남 창녕  경남       창녕    36,586
254  경남 창원 마산합포  경남  창원 마산합포    98,848
255  경남 창원 마산회원  경남  창원 마산회원   101,587
256    경남 창원 성산  경남    창원 성산   200,206
257    경남 창원 의창  경남    창원 의창   120,323
258    경남 창원 진해  경남    창원 진해    95,316
259       경남 통영  경남       통영    54,182
260       경남 하동  경남       하동    24,587
261       경남 함안  경남       함안    64,756
262       경남 함양  경남       함양    20,244
263       경남 합천  경남       합천    24,342
265      제주 서귀포  제주      서귀포   107,598
266       제주 제주  제주       제주   544,015

In [68]:
df.to_excel(excel_writer='address.xlsx',encoding = 'cp949')

In [69]:
# key : E07005C0-0CEE-30AC-B9D7-84F23F520E05
#-*-coding: utf-8 -*-
import requests
import openpyxl
import json

## 엑셀 파일 오픈
filename = "address.xlsx"
exelFile = openpyxl.load_workbook(filename)

## 시트 설정
sheet = exelFile.worksheets[0]

## 데이터 가져오기
rowCount = 1
for row in sheet.rows:	

	try:
		## geocoder 호출
		r = requests.get("http://apis.vworld.kr/new2coord.do?q="+row[0].value+"&output=json&epsg=epsg:4326&apiKey=E07005C0-0CEE-30AC-B9D7-84F23F520E05")

		## cell 설정 [ (10)J1 ~ J* : 위도 / (11)K1 ~ K* : 경도]
		lat_cell = sheet.cell(row = rowCount, column = 2)
		lng_cell = sheet.cell(row = rowCount, column = 3)

		## 데이터 추가
		lat_cell.value = r.json()["EPSG_4326_Y"]
		lng_cell.value = r.json()["EPSG_4326_X"]
	except KeyError as ke:
		lat_cell.value = 0
		lng_cell.value = 0
	except TypeError as te:
		lat_cell.value = 0
		lng_cell.value = 0
		
	rowCount = rowCount + 1

## 데이터 저장
exelFile.save("address.xlsx")

In [70]:
df_1 = pd.read_csv('./address.csv')
df_1

            시군구         위도          경도 자동차 등록 현황
0         서울 강남  37.493701  127.083371   238,244
1         서울 강동  37.555168  127.143874   152,372
2         서울 강북  37.639463  127.008987    75,389
3         서울 강서  37.551006  126.870087   204,285
4         서울 관악  37.483956  126.915163   118,529
5         서울 광진  37.548584  127.070242    98,364
6         서울 구로  37.495338  126.856767   145,204
7         서울 금천  37.458239  126.893670    89,891
8         서울 노원  37.618208  127.075908   152,145
9         서울 도봉  37.665236  127.038871    95,745
10       서울 동대문  37.576716  127.049782    98,427
11        서울 동작  37.512368  126.938567   106,156
12        서울 마포  37.552216  126.955504   121,224
13       서울 서대문  37.582739  126.928110    89,451
14        서울 서초  37.484007  127.020679   177,928
15        서울 성동  37.537628  127.092751   106,348
16        서울 성북  37.610399  127.052592   121,263
17        서울 송파  37.503385  127.110514   246,647
18        서울 양천  37.534838  126.826300   151,317
19       서울 영등포  37.523817  126.905671   146,188
20        서울 용산  37.539319  126.963097    79,619
21        서울 은평  37.635289  126.917594   132,712
22        서울 종로  37.573412  127.022380    50,258
23         서울 중  37.566701  126.978347    61,930
24        서울 중랑  37.587253  127.086345   114,325
25        부산 강서  35.087420  128.853779    85,620
26        부산 금정  35.212756  129.099614    88,347
27        부산 기장  35.236144  129.214575    83,626
28         부산 남  35.087420  128.853779   100,847
29         부산 동  35.087420  128.853779    57,009
30        부산 동래  35.213598  129.076594    96,440
31       부산 부산진  35.151517  129.065894   143,182
32         부산 북  35.087420  128.853779   106,063
33        부산 사상  35.163244  128.985557    89,145
34        부산 사하  35.080967  128.986317   113,846
35         부산 서  35.087420  128.853779    30,681
36        부산 수영  35.176790  129.101455   104,965
37        부산 연제  35.183789  129.072425   104,488
38        부산 영도  35.092149  129.037705    33,470
39         부산 중  35.087420  128.853779    37,426
40       부산 해운대  35.162236  129.168521   181,829
41         대구 남  35.841187  128.561332    57,794
42        대구 달서  35.838805  128.536169   286,275
43        대구 달성  35.655825  128.415611   141,955
44         대구 동  35.841187  128.561332   166,008
45         대구 북  35.841187  128.561332   210,306
46         대구 서  35.841187  128.561332    72,207
47        대구 수성  35.866210  128.641900   214,023
48         대구 중  35.841187  128.561332    61,368
49        인천 강화  37.744851  126.494673    53,600
50        인천 계양  37.541736  126.738856   304,413
51        인천 남동  37.462874  126.734917   306,100
52         인천 동  37.545468  126.676068    27,486
53       인천 미추홀  37.468191  126.663722   169,090
54        인천 부평  37.482860  126.708348   249,518
55         인천 서  37.545468  126.676068   258,220
56        인천 연수  37.416908  126.676947   208,286
57        인천 옹진  37.254523  126.308336    12,686
58         인천 중  37.545468  126.676068    80,045
59        광주 광산  35.237160  126.738571   210,391
60         광주 남  35.174291  126.912124    94,984
61         광주 동  35.174291  126.912124    45,031
62         광주 북  35.174291  126.912124   200,103
63         광주 서  35.174291  126.912124   147,924
64        대전 대덕  36.452868  127.427803    93,017
65         대전 동  36.268065  127.472338    96,524
66         대전 서  36.268065  127.472338   215,663
67        대전 유성  36.358531  127.347431   183,762
68         대전 중  36.268065  127.472338   102,115
69         울산 남  35.538044  129.348394   161,974
70         울산 동  35.538044  129.348394    63,179
71         울산 북  35.538044  129.348394   119,296
72        울산 울주  35.551674  129.250956   132,244
73         울산 중  35.538044  129.348394   103,132
74    세종 세종특별자치  36.491854  127.254597   182,919
75        경기 가평  37.677543  127.484453    32,295
76     경기 고양 덕양  37.626698  126.870728   188,121
77    경기 고양 일산동  37.686882  126.770675   131,845
78    경기 고양 일산서  37.664545  126.754523   121,238
79        경기 과천  37.437764  126.999613    27,306
80        경기 광명  37.470362  126.872502   105,277
81        경기 광주  37.398515  127.270194   204,116
82        경기 구리  37.605949  127.135550    73,443
83        경기 군포  37.357058  126.949205   103,749
84        경기 김포  37.604391  126.767525   237,235
85       경기 남양주  37.607307  127.152810   315,280
86       경기 동두천  37.927363  127.053401    40,140
87        경기 부천  37.483680  126.772664   308,449
88     경기 성남 분당  37.404372  127.109009   194,196
89     경기 성남 수정  37.444301  127.141380    79,981
90     경기 성남 중원  37.434598  127.136504    75,968
91     경기 수원 권선  37.258357  127.009189   200,691
92     경기 수원 영통  37.233811  127.047934   150,880
93     경기 수원 장안  37.314403  126.983248   107,347
94     경기 수원 팔달  37.288934  126.998724    76,726
95        경기 시흥  37.366929  126.814324   261,394
96     경기 안산 단원  37.311460  126.824929   165,736
97     경기 안산 상록  37.284665  126.848072   149,567
98        경기 안성  37.019066  127.260447   112,090
99     경기 안양 동안  37.380334  126.952575   123,733
100    경기 안양 만안  37.418768  126.909985    88,643
101       경기 양주  37.656641  127.143408   114,944
102       경기 양평  37.496047  127.492754    64,065
103       경기 여주  37.313654  127.638982    71,807
104       경기 연천  38.079921  127.074926    29,479
105       경기 오산  37.133258  127.073028   112,258
106    경기 용인 기흥  37.266470  127.095694   196,947
107    경기 용인 수지  37.341567  127.100062   148,793
108    경기 용인 처인  37.154662  127.167114   142,619
109       경기 의왕  37.386841  126.977868    69,082
110      경기 의정부  37.730008  127.037490   172,149
111       경기 이천  37.251659  127.359760   122,790
112       경기 파주  37.761253  126.774717   233,754
113       경기 평택  37.009716  127.088743   309,131
114       경기 포천  37.893691  127.191382    98,262
115       경기 하남  37.538061  127.197253   134,572
116       경기 화성  37.204769  127.037799   475,924
117       강원 강릉  37.768356  128.885093   114,677
118       강원 고성  38.254110  128.559928    15,269
119       강원 동해  37.479489  129.121622    47,787
120       강원 삼척  37.450848  129.155509    33,483
121       강원 속초  38.201032  128.581458    40,549
122       강원 양구  38.132479  127.988170    12,442
123       강원 양양  38.079068  128.621614    16,636
124       강원 영월  37.129144  128.829157    22,039
125       강원 원주  37.354374  127.919768   184,141
126       강원 인제  38.071398  128.178147    19,394
127       강원 정선  37.378676  128.664137    21,477
128       강원 철원  38.142762  127.303353    24,814
129       강원 춘천  37.852781  127.735501   142,226
130       강원 태백  37.099782  129.006164    20,821
131       강원 평창  37.662306  128.662551    26,493
132       강원 홍천  37.714903  127.905149    40,722
133       강원 화천  38.113094  127.699110    13,550
134       강원 횡성  37.484412  127.980460    28,081
135       충북 괴산  36.811754  127.790913    23,507
136       충북 단양  36.988827  128.363537    16,629
137       충북 보은  36.485073  127.726084    19,409
138       충북 영동  36.171524  127.787645    25,579
139       충북 옥천  36.292312  127.570978    28,864
140       충북 음성  36.930641  127.695328    61,100
141       충북 제천  37.162222  128.186006    71,360
142       충북 증평  36.785049  127.581036    20,156
143       충북 진천  36.988108  127.444604    52,368
144       충북 청원  36.622556  127.365487        20
145    충북 청주 상당  36.601128  127.500968    96,603
146    충북 청주 서원  36.618899  127.448193   106,419
147    충북 청주 청원  36.622556  127.365487   108,824
148    충북 청주 흥덕  36.648353  127.483211   139,764
149       충북 충주  36.988398  127.829486   118,935
150       충남 계룡  36.269192  127.268993    23,253
151       충남 공주  36.475445  127.131968    57,169
152       충남 금산  36.111260  127.486620    30,934
153       충남 논산  36.190591  127.090204    63,884
154       충남 당진  36.883450  126.643083   101,049
155       충남 보령  36.352424  126.616710    54,380
156       충남 부여  36.274082  126.877488    35,791
157       충남 서산  36.782451  126.466216   100,543
158       충남 서천  36.085758  126.684914    28,152
159       충남 아산  36.795020  127.009568   180,809
160       충남 예산  36.687915  126.831087    45,119
161    충남 천안 동남  36.827057  127.155958   137,275
162    충남 천안 서북  36.834609  127.150115   204,817
163       충남 청양  36.459079  126.802334    18,008
164       충남 태안  36.750152  126.296384    35,164
165       충남 홍성  36.599956  126.671663    55,246
166       전북 고창  35.433913  126.693922    31,491
167       전북 군산  35.979526  126.739299   138,743
168       전북 김제  35.798257  126.904256    47,860
169       전북 남원  35.423846  127.408111    45,299
170       전북 무주  36.009246  127.664943    13,527
171       전북 부안  35.721831  126.734267    28,267
172       전북 순창  35.374467  127.137399    15,027
173       전북 완주  35.944122  127.127551    55,615
174       전북 익산  35.959910  126.989015   143,138
175       전북 임실  35.611160  127.279244    14,873
176       전북 장수  35.649155  127.514886    12,633
177    전북 전주 덕진  35.839424  127.113499   180,598
178    전북 전주 완산  35.782043  127.129522   157,354
179       전북 정읍  35.555137  126.861749    58,829
180       전북 진안  35.794261  127.438397    14,596
181       전남 강진  34.640438  126.764776    19,980
182       전남 고흥  34.524344  127.139937    33,209
183       전남 곡성  35.284250  127.289417    15,820
184       전남 광양  34.968737  127.611634    90,309
185       전남 구례  35.213398  127.462107    14,033
186       전남 나주  35.041996  126.850519    69,579
187       전남 담양  35.310099  126.987623    29,299
188       전남 목포  34.806786  126.445769   100,383
189       전남 무안  34.990432  126.481677    51,055
190       전남 보성  34.771480  127.082682    35,265
191       전남 순천  34.985511  127.498375   147,555
192       전남 신안  34.806001  126.366477   100,689
193       전남 여수  34.743423  127.742235   139,779
194       전남 영광  35.279365  126.497803    28,919
195       전남 영암  34.746071  126.464252    36,401
196       전남 완도  34.312463  126.758026    26,297
197       전남 장성  35.304717  126.783238    28,139
198       전남 장흥  34.684397  126.912116    20,782
199       전남 진도  34.477235  126.263204    17,523
200       전남 함평  35.063982  126.517972    49,753
201       전남 해남  34.568427  126.608148    70,495
202       전남 화순  35.059106  126.991020    35,545
203       경북 경산  35.817582  128.731691   144,466
204       경북 경주  35.856920  129.220717   147,420
205       경북 고령  35.823260  128.449992    21,284
206       경북 구미  36.158922  128.339357   221,876
207       경북 군위  36.239041  128.567378    15,336
208       경북 김천  36.136738  128.113706    77,457
209       경북 문경  36.586141  128.188666    38,271
210       경북 봉화  36.910960  128.739408    18,494
211       경북 상주  36.408862  128.150169    55,309
212       경북 성주  35.923651  128.279913    32,265
213       경북 안동  36.560860  128.704040    86,301
214       경북 영덕  36.409825  129.373566    19,551
215       경북 영양  36.666721  129.112430    10,095
216       경북 영주  36.827067  128.611351    57,463
217       경북 영천  35.966892  128.943213    63,005
218       경북 예천  36.660677  128.466516    31,254
219       경북 울릉  37.491200  130.912703     5,946
220       경북 울진  36.991427  129.404539    26,996
221       경북 의성  36.357364  128.700056    32,335
222       경북 청도  35.666404  128.665809    26,068
223       경북 청송  36.427674  129.055896    16,212
224       경북 칠곡  35.977834  128.403393    71,509
225     경북 포항 남  35.982020  129.445038   130,961
226     경북 포항 북  35.982020  129.445038   145,091
227       경남 거제  34.897879  128.563800   108,939
228       경남 거창  35.687962  127.903912    33,598
229       경남 고성  34.976529  128.311525    27,309
230       경남 김해  35.239354  128.885799   284,617
231       경남 남해  34.837698  127.892652    20,773
232       경남 밀양  35.504017  128.734759    60,453
233       경남 사천  35.061342  128.069286    58,517
234       경남 산청  35.415024  127.879262    21,396
235       경남 양산  35.347590  129.022367   178,813
236       경남 의령  35.321199  128.260438    15,662
237       경남 진주  35.219811  128.148225   174,010
238       경남 창녕  35.509365  128.507659    36,586
239  경남 창원 마산합포  35.217335  128.586679    98,848
240  경남 창원 마산회원  35.222667  128.572896   101,587
241    경남 창원 성산  35.208388  128.690945   200,206
242    경남 창원 의창  35.253560  128.515260   120,323
243    경남 창원 진해  35.120052  128.779766    95,316
244       경남 통영  34.879802  128.418667    54,182
245       경남 하동  34.960017  127.773692    24,587
246       경남 함안  35.276787  128.400902    64,756
247       경남 함양  35.523599  127.730322    20,244
248       경남 합천  35.575670  128.164540    24,342
249      제주 서귀포  33.249587  126.523655   107,598
250       제주 제주  33.253665  126.510034   544,015